name: Generate Snake Animation

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate Snake Animation
      id: generate
      uses: Sutil/snk@v01.00.02
      with:
        github_user_name: GB-Navarro
        svg_out_path: snake.svg

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: snake-svg
        path: snake.svg
